export const UPDATE_SS_LIMIT = 'UPDATE_SS_LIMIT';
export const SELECT_FACTION = 'SELECT_FACTION';
export const REQUEST_CHARS = 'REQUEST_CHARS';
export const RECEIVE_CHARS = 'RECEIVE_CHARS';
export const TOGGLE_LEADER = 'TOGGLE_LEADER';
export const TOGGLE_FOLLOWER = 'TOGGLE_FOLLOWER';
